export const admin = {
    users : [
        {
            _id: "66ab5c4881f639d8c84d0ec1",
            name: "John Doe",
            email: "john@gmail.com",
            role: "cook",
            phone: "1234567890",
            address: "Mandir Street",
            profilePicture: '',
            dateOfBirth: "2000-10-22T00:00:00.000Z",
            isActive: false,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec2",
            name: "Jane Smith",
            email: "jane@gmail.com",
            role: "waiter",
            phone: "9876543210",
            address: "Temple Road",
            profilePicture: '',
            dateOfBirth: "1995-05-16T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec3",
            name: "Alex Johnson",
            email: "alex@gmail.com",
            role: "manager",
            phone: "1231231234",
            address: "Market Lane",
            profilePicture: '',
            dateOfBirth: "1990-02-10T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec4",
            name: "Emma Williams",
            email: "emma@gmail.com",
            role: "cook",
            phone: "4564564567",
            address: "Church Avenue",
            profilePicture: '',
            dateOfBirth: "1988-12-14T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec5",
            name: "Michael Brown",
            email: "michael@gmail.com",
            role: "waiter",
            phone: "7897897890",
            address: "High Street",
            profilePicture: '',
            dateOfBirth: "1999-07-21T00:00:00.000Z",
            isActive: false,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec6",
            name: "Sophia Taylor",
            email: "sophia@gmail.com",
            role: "manager",
            phone: "3213213210",
            address: "Park Lane",
            profilePicture: '',
            dateOfBirth: "1992-09-05T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec7",
            name: "James Anderson",
            email: "james@gmail.com",
            role: "cook",
            phone: "6546546543",
            address: "Main Street",
            profilePicture: '',
            dateOfBirth: "1985-01-30T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec8",
            name: "Olivia Martinez",
            email: "olivia@gmail.com",
            role: "waiter",
            phone: "2342342345",
            address: "Broadway",
            profilePicture: '',
            dateOfBirth: "1997-11-03T00:00:00.000Z",
            isActive: false,
        },
        {
            _id: "66ab5c4881f639d8c84d0ec9",
            name: "William Harris",
            email: "william@gmail.com",
            role: "cook",
            phone: "5675675678",
            address: "Elm Street",
            profilePicture: '',
            dateOfBirth: "1993-04-18T00:00:00.000Z",
            isActive: true,
        },
        {
            _id: "66ab5c4881f639d8c84d0eca",
            name: "Isabella Lewis",
            email: "isabella@gmail.com",
            role: "manager",
            phone: "4324324321",
            address: "River Road",
            profilePicture: '',
            dateOfBirth: "2001-08-12T00:00:00.000Z",
            isActive: false,
        },
    ],

    dishes: [
        {
            _id: 2345678,
            name: 'Chicken Burger',
            foodType: 'Nonveg',
            description: 'Juicy chicken patty with fresh lettuce and spicy mayo.',
            servingSize: [
                { _id: 234543, size: 'Small', price: 50 },
                { _id: 2345432, size: 'Medium', price: 100 },
                { _id: 2345431, size: 'Large', price: 200 },
            ],
            tags: ["chef's special", "Burger", "Spicy"],
            category: "Burgers",
            image: '',
            available: true,
        },
        {
            _id: 2345679,
            name: 'Veggie Pizza',
            foodType: 'Veg',
            description: 'Crispy crust with fresh veggies and mozzarella cheese.',
            servingSize: [
                { _id: 234544, size: 'Small', price: 150 },
                { _id: 2345442, size: 'Medium', price: 250 },
                { _id: 2345441, size: 'Large', price: 400 },
            ],
            tags: ["Pizza", "Vegetarian", "Cheesy"],
            category: "Pizza",
            image: '',
            available: true,
        },
        {
            _id: 2345680,
            name: 'Beef Steak',
            foodType: 'Nonveg',
            description: 'Tender beef steak with garlic butter sauce.',
            servingSize: [
                { _id: 234545, size: 'Small', price: 500 },
                { _id: 2345452, size: 'Medium', price: 800 },
                { _id: 2345451, size: 'Large', price: 1000 },
            ],
            tags: ["Steak", "Beef", "Chef's Special"],
            category: "Main Course",
            image: '',
            available: false,
        },
        {
            _id: 2345681,
            name: 'Caesar Salad',
            foodType: 'Veg',
            description: 'Crisp romaine lettuce with Caesar dressing and croutons.',
            servingSize: [
                { _id: 234546, size: 'Small', price: 100 },
                { _id: 2345462, size: 'Medium', price: 150 },
                { _id: 2345461, size: 'Large', price: 200 },
            ],
            tags: ["Salad", "Healthy", "Vegetarian"],
            category: "Salads",
            image: '',
            available: true,
        },
        {
            _id: 2345682,
            name: 'Grilled Salmon',
            foodType: 'Nonveg',
            description: 'Grilled salmon served with a lemon butter sauce.',
            servingSize: [
                { _id: 234547, size: 'Small', price: 700 },
                { _id: 2345472, size: 'Medium', price: 1000 },
                { _id: 2345471, size: 'Large', price: 1300 },
            ],
            tags: ["Seafood", "Salmon", "Grilled"],
            category: "Main Course",
            image: '',
            available: true,
        },
        {
            _id: 2345683,
            name: 'Penne Alfredo',
            foodType: 'Veg',
            description: 'Creamy Alfredo sauce with perfectly cooked penne pasta.',
            servingSize: [
                { _id: 234548, size: 'Small', price: 200 },
                { _id: 2345482, size: 'Medium', price: 350 },
                { _id: 2345481, size: 'Large', price: 500 },
            ],
            tags: ["Pasta", "Vegetarian", "Creamy"],
            category: "Pasta",
            image: '',
            available: true,
        },
        {
            _id: 2345684,
            name: 'Margarita Pizza',
            foodType: 'Veg',
            description: 'Classic Margarita pizza with fresh basil and mozzarella.',
            servingSize: [
                { _id: 234549, size: 'Small', price: 150 },
                { _id: 2345492, size: 'Medium', price: 300 },
                { _id: 2345491, size: 'Large', price: 450 },
            ],
            tags: ["Pizza", "Vegetarian", "Cheesy"],
            category: "Pizza",
            image: '',
            available: true,
        },
        {
            _id: 2345685,
            name: 'Spaghetti Bolognese',
            foodType: 'Nonveg',
            description: 'Rich tomato-based sauce with ground beef and spaghetti.',
            servingSize: [
                { _id: 234550, size: 'Small', price: 250 },
                { _id: 2345502, size: 'Medium', price: 400 },
                { _id: 2345501, size: 'Large', price: 600 },
            ],
            tags: ["Pasta", "Beef", "Tomato Sauce"],
            category: "Pasta",
            image: '',
            available: true,
        },
        {
            _id: 2345686,
            name: 'Fish Tacos',
            foodType: 'Nonveg',
            description: 'Soft tacos filled with crispy fish and tangy slaw.',
            servingSize: [
                { _id: 234551, size: 'Small', price: 300 },
                { _id: 2345512, size: 'Medium', price: 500 },
                { _id: 2345511, size: 'Large', price: 700 },
            ],
            tags: ["Tacos", "Seafood", "Spicy"],
            category: "Tacos",
            image: '',
            available: false,
        },
        {
            _id: 2345687,
            name: 'Chocolate Lava Cake',
            foodType: 'Veg',
            description: 'Rich chocolate cake with molten center.',
            servingSize: [
                { _id: 234552, size: 'Small', price: 150 },
                { _id: 2345522, size: 'Medium', price: 250 },
                { _id: 2345521, size: 'Large', price: 350 },
            ],
            tags: ["Dessert", "Chocolate", "Cake"],
            category: "Desserts",
            image: '',
            available: true,
        },
    ],
    tables: [  
        {    seating: 'A',    tableNumber: 1,    booked: true,    chairs: 6  },
        {    seating: 'A',    tableNumber: 2,    booked: false,    chairs: 4  },  
        {    seating: 'A',    tableNumber: 3,    booked: true,    chairs: 3  },
        {    seating: 'B',    tableNumber: 1,    booked: true,    chairs: 6  },
        {    seating: 'B',    tableNumber: 2,    booked: false,    chairs: 4  },  
        {    seating: 'B',    tableNumber: 3,    booked: true,    chairs: 3  },
        {    seating: 'C',    tableNumber: 1,    booked: true,    chairs: 6  },
        {    seating: 'C',    tableNumber: 2,    booked: false,    chairs: 4  },  
        {    seating: 'C',    tableNumber: 3,    booked: true,    chairs: 8  }

    ],  
}
