export { default as Dish } from './dish/Dish';
export { default as ChefSpecial } from './chefSpecial/ChefSpecial';
export { default as SwitchButton } from './switchButton/SwitchButton';
export { default as MobileSearch } from './mobileSearch/MobileSearch';
export { default as ProfileButton } from './profileButton/ProfileButton';
export { default as NavigationTab } from './navigationTab/NavigationTab';
export { default as TextInputField } from './textInputField/TextInputField';
export { default as SendOtpButton } from './sendOtpButton/SendOtpButton';
export { default as SubmitButton } from './submitButton/SubmitButton';
export { default as  ServingSize} from './servingSize/ServingSize';
export { default as HorizontalLine } from './horizontalLine/HorizontalLine';
export { default as DesktopNavTab } from './desktopNavTab/DesktopNavTab';
export { default as DesktopProfile } from './desktopProfile/DesktopProfile';
export { default as OrderCard } from './orderCard/OrderCard';
export { default as OrdersOnTable } from './ordersOnTable/OrdersOnTable';
export { default as DesktopSearch } from './desktopSearch/DesktopSearch';
// export { default as CurrentStatus } from './currentStatus/CurrentStatus';
export { default as UsersTable } from './usersTable/UsersTable';
export { default as DishesTable } from './dishesTable/DishesTable';
export { default as TablesTable } from './tablesTable/TablesTable';
export { default as PaymentMethods } from './paymentMethods/PaymentMethods';
export { default as OrdersTable } from './ordersTable/OrdersTable';
export { default as DeleteModal } from './deleteModal/DeleteModal';
export { default as EditModal } from './editDish/EditDish';
export { default as OrderSummary } from './orderSummary/OrderSummary';
export { default as BillTemplate } from './billTemplate/BillTemplate';